name: auto-merge
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
permissions:
  pull-requests: write
  contents: write
jobs:
  merge:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'automerge') && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --auto --delete-branch
