name: required-check
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
jobs:
  required-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo ok
